apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-basics.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "node-basics.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "node-basics.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
