version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile-Local
      context: .
    env_file:
      - .env
    ports:
      - "8080:3000"
    volumes:
      - ./src:/app/src:rw
      - ./tests:/app/tests:rw
      - ./.env:/app/.env:ro
    command: npm run dev
